version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/deploy/
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: execute-deploy.sh
      timeout: 180