spring:
  config:
    activate:
      on-profile: prod

  logging:
    level:
      root: INFO  # 전체 애플리케이션의 기본 로그 레벨
      com.itschool.tableq: DEBUG  # 특정 패키지의 로그 레벨 설정 (예: 디버깅이 필요한 패키지에 대해 DEBUG)
    file:
      name: /home/ec2-user/app/log/application.log  # 로그 파일 경로 설정
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%t] %c{1}:%L - %m%n"  # 콘솔 출력 패턴
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 파일 출력 패턴

  h2:
    console:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 'update'로 변경
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용

      #hibernate:
      #ddl-auto: create  # 운영 환경에서는 update로 변경
      #properties:
      #hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용

    // 패스워드 인코더로 사용할 빈 등록
    @Bean
    public BCryptPasswordEncoder bCryptPasswordEncoder() {
    return new BCryptPasswordEncoder();
  }
  }
