app:
  version: 1.0.5

server:
  port: 8080

# Choose Environment
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: prod
  # config:
  # location: classpath:/application-dev.yml