spring:
  config:
    activate:
      on-profile: dev  # dev 프로파일에서만 적용

  datasource:
    url: jdbc:postgresql://192.168.1.168:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate  # 스키마 자동 변경, 개발 환경에서 주로 사용
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    group-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

cloud:
  aws:
    s3:
      bucket: tableq-bucket             # 버킷 이름
    stack.auto: false                   # 자동 스택 관리 여부 (true로 설정하면 자동 관리)
    region.static: ap-northeast-2       # AWS 서울 지역 (ap-northeast-2)
    credentials:
      access-Key: ${AWS_ACCESS_KEY_ID}
      secret-Key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    root: INFO
    com.itschool.tableq: DEBUG  # 개발 환경에서 더 많은 디버그 정보 출력
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 콘솔 로그 패턴
