app:
  version: 1.0.4

server:
  port: 80

# Choose Environment
spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: prod
  # config:
  # location: classpath:/application-dev.yml