spring:
  config:
    activate:
      on-profile: local  # local 프로파일에서만 적용
  h2:
    console:
      enabled: true  # /h2-console 접속 가능
  datasource:
    url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        ddl-auto: create  # 매번 스키마 생성 (개발/로컬 환경에 적합)
        dialect: org.hibernate.dialect.H2Dialect  # H2 방언 사용
    defer-datasource-initialization: true  # 데이터 소스 초기화를 지연
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

  logging:
    level:
      root: INFO
      com.itschool.tableq: DEBUG  # 필요한 로그 레벨로 설정
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 콘솔 로그 패턴 (필요에 따라 수정)

springdoc:
  swagger-ui:
    path: /swagger-ui
    group-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

cloud:
  aws:
    s3:
      bucket: tableq-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-Key: ${AWS_ACCESS_KEY_ID}
      secret-Key: ${AWS_SECRET_ACCESS_KEY}
