spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    # 운영 환경에서는 SQL 로그를 출력하지 않는 것이 좋음
    hibernate:
      ddl-auto: create  # 운영 환경에서는 update로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용

cloud:
  aws:
    s3:
      bucket: tableq-file-bucket             # 버킷 이름
    stack.auto: false                   # 자동 스택 관리 여부 (true로 설정하면 자동 관리)
    region.static: ap-northeast-2       # AWS 서울 지역 (ap-northeast-2)
    credentials:
      access-Key: ${AWS_ACCESS_KEY_ID}
      secret-Key: ${AWS_SECRET_ACCESS_KEY}